#!/groovy
pipeline{
	agent any

	environment {
		REPOSITORY="https://github.com/zhangfuli/ablock.git"
		SERVICE_DIR="ablock-test"
		DOCKER_REGISTRY="zhangfuli/ablock-test"
	}

	stages {
		stage('获取代码') {
			steps {
				echo "start fetch code from git:${REPOSITORY}"
				deleteDir()
				git "${REPOSITORY}"
                script {
                    time = sh(returnStdout: true, script: 'date "+%Y%m%d%H%M"').trim()
                    git_version = sh(returnStdout: true, script: 'git log -1 --pretty=format:"%h"').trim()
                    build_tag = time+git_version
                }
			}
		}

		stage('编译+单元测试') {
			steps {
                echo "star compile"
                dir(SERVICE_DIR){
                    sh "pwd"
                    sh "ls -l"
                    sh "mvn -U -am clean package"
                }
			}
		}

		stage('构建镜像') {
			steps {
                echo "start build image"
                echo "image tag : ${build_tag}"
                dir(SERVICE_DIR){
                    sh "ls -l"
                    sh "docker build -t ${DOCKER_REGISTRY}:${build_tag} ."
                }
			}
		}

       stage('推送镜像') {
            steps {
                echo "start push image"
                dir(SERVICE_DIR){
                  sh "ls -l"
                  withCredentials([usernamePassword(credentialsId: 'docker_registry', passwordVariable: 'docker_registryPassword', usernameVariable: 'docker_registryUsername')]) {
                      sh "docker login -u ${docker_registryUsername} -p ${docker_registryPassword}"
                      sh "docker push ${DOCKER_REGISTRY}:${build_tag}"
                  }
                }
            }
        }
	    stage('发布系统') {
			steps {
				echo "start deploy"
				dir(SERVICE_DIR){
				    sh "ls -l"
				    script {
                        docker_id = sh(returnStdout: true, script: 'docker ps --filter name=ablock-test -q').trim()
                        if (docker_id == '') {
                            sh "docker run -ti -d --name ablock-test -p 3001:8080 ${DOCKER_REGISTRY}:${build_tag}"
                        }else{
                            sh "docker stop ablock-test"
                            sh "docker rm ablock-test"
                            sh "docker run -ti -d --name ablock-test -p 3001:8080 ${DOCKER_REGISTRY}:${build_tag}"
                        }
                    }
				}
			}
		}
	}
}